/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SlotMachine;

import java.awt.Color;

/**
 *
 * @author magnus
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }
    
    Slot slot1 = new Slot();
    Slot slot2 = new Slot();
    Slot slot3 = new Slot();
    
    int rollsLeft = 3;
    int scoring = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSlot1 = new javax.swing.JLabel();
        txtSlot2 = new javax.swing.JLabel();
        txtSlot3 = new javax.swing.JLabel();
        btnHold1 = new javax.swing.JButton();
        btnHold2 = new javax.swing.JButton();
        btnHold3 = new javax.swing.JButton();
        btnRoll = new javax.swing.JButton();
        txtRollsLeft = new javax.swing.JLabel();
        txtPoints = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSlot1.setText("Empty");

        txtSlot2.setText("Empty");

        txtSlot3.setText("Empty");

        btnHold1.setText("Hold");
        btnHold1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHold1ActionPerformed(evt);
            }
        });

        btnHold2.setText("Hold");
        btnHold2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHold2ActionPerformed(evt);
            }
        });

        btnHold3.setText("Hold");
        btnHold3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHold3ActionPerformed(evt);
            }
        });

        btnRoll.setText("Roll");
        btnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollActionPerformed(evt);
            }
        });

        txtRollsLeft.setText("Rolls left: 3");

        txtPoints.setText("Points: 0");

        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("<html>\nApple = 10 points<br>\nBanana = 30 points<br>\nStar = 50 points<br><br>\nRe-roll = lose 5 points\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(txtSlot1)
                        .addGap(33, 33, 33)
                        .addComponent(txtSlot2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSlot3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPoints)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHold1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHold2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHold3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRollsLeft)
                    .addComponent(btnRoll))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSlot1)
                    .addComponent(txtSlot2)
                    .addComponent(txtSlot3)
                    .addComponent(btnRoll))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHold1)
                        .addComponent(btnHold2)
                        .addComponent(btnHold3))
                    .addComponent(txtRollsLeft))
                .addGap(18, 18, 18)
                .addComponent(txtPoints)
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollActionPerformed

        if(rollsLeft == 0) {
            
            //Scoring
            if(slot1.getFace() == "Apple" && slot2.getFace() == "Apple" && slot3.getFace() == "Apple") {
                scoring += 10;
            } else if(slot1.getFace() == "Banana" && slot2.getFace() == "Banana" && slot3.getFace() == "Banana") {
                scoring += 30;
            } else if(slot1.getFace() == "Star" && slot2.getFace() == "Star" && slot3.getFace() == "Star") {
                scoring += 50;
            }
            
            rollsLeft = 3;
            
            slot1.setLocked(false);
            slot2.setLocked(false);
            slot3.setLocked(false);
            
            txtSlot1.setForeground(Color.black);
            txtSlot2.setForeground(Color.black);
            txtSlot3.setForeground(Color.black);
            
            //Lose points if rolling again
            scoring -= 5;
            
            //Resetting slots to avoid locking in points every time
            slot1.setFace("Empty");
            slot2.setFace("Empty");
            slot3.setFace("Empty");
            
            txtSlot1.setText(slot1.getFace());
            txtSlot2.setText(slot2.getFace());
            txtSlot3.setText(slot3.getFace());
            
            //Printing points
            txtPoints.setText("Points: " + scoring);
            
            
        } else {
            if(!slot1.isLocked()) {
                slot1.setFace(slot1.spin());
            }

            if(!slot2.isLocked()) {
                slot2.setFace(slot2.spin());
            }

            if(!slot3.isLocked()) {
                slot3.setFace(slot3.spin());
            }

            txtSlot1.setText(slot1.getFace());
            txtSlot2.setText(slot2.getFace());
            txtSlot3.setText(slot3.getFace());

            rollsLeft--;
            txtRollsLeft.setText("Rolls left: " + rollsLeft);
        }
        
    }//GEN-LAST:event_btnRollActionPerformed

    //TODO Use if-sentence to be able to unlock the slots
    
    private void btnHold1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHold1ActionPerformed
        slot1.setLocked(true);
        txtSlot1.setForeground(Color.blue);
    }//GEN-LAST:event_btnHold1ActionPerformed

    private void btnHold2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHold2ActionPerformed
        slot2.setLocked(true);
        txtSlot2.setForeground(Color.blue);
    }//GEN-LAST:event_btnHold2ActionPerformed

    private void btnHold3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHold3ActionPerformed
        slot3.setLocked(true);
        txtSlot3.setForeground(Color.blue);
    }//GEN-LAST:event_btnHold3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHold1;
    private javax.swing.JButton btnHold2;
    private javax.swing.JButton btnHold3;
    private javax.swing.JButton btnRoll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtPoints;
    private javax.swing.JLabel txtRollsLeft;
    private javax.swing.JLabel txtSlot1;
    private javax.swing.JLabel txtSlot2;
    private javax.swing.JLabel txtSlot3;
    // End of variables declaration//GEN-END:variables
}
